# server
server:
  port: 10010
  servlet:
    context-path: /ams
# spring
spring:
  # datasource
  datasource:
    url: jdbc:mariadb://maria-database.ciroumm1ym9r.ap-northeast-2.rds.amazonaws.com:3306
    name: AMS
    username: admin
    password: admin1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
  # jpa
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true