# server
server:
  port: 10010
  servlet:
    context-path: /ams

# spring
spring:
  # jpa
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  # mvc
  mvc:
    path-match:
      matching-strategy: ant_path_matcher